### ISSUE TITLE
Investigate Connect Gateway as an alternative for VPN based approach

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/terraform-google-secure-cicd#20]
Investigate https://cloud.google.com/anthos/multicluster-management/gateway/tutorials/cloud-build-integration as the default which maybe simpler and cost effective than https://github.com/GoogleCloudPlatform/terraform-google-secure-cicd/tree/main/modules/workerpool-gke-ha-vpn

**Comment by morgante** [comment]
Unfortunately Connect Gateway currently requires (a) Anthos licensing and (b) the hub membership must be created via gcloud. I'm investigating in b/227658842.

**Comment by gtsorbo** [comment]
Addressed in https://github.com/GoogleCloudPlatform/terraform-google-secure-cicd/pull/59
