### ISSUE TITLE
Use upstream registry ref for standalone_single_project module

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/terraform-google-secure-cicd#32]
We should use the upstream registry link for standalone_single_project rather than the relative path so it is fully standalone with no dependencies. For this we should
- [x] Cut a 0.2.0 release with changes
- [x] Use released module in example
- [x] Update build pipeline to use [module swapper](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/infra/build/developer-tools/build/scripts/module-swapper) so while testing it will swap the module reference to local. [Example](https://github.com/terraform-google-modules/terraform-google-network/blob/a93fd8ba6075dff58abdd3dbcb4487c29abc7168/build/int.cloudbuild.yaml#L17-L19)

**Comment by gtsorbo** [comment]
Fixed in #33
